worker_processes auto;
worker_rlimit_nofile 65536;
error_log stderr error;
timer_resolution 1s;
daemon off;
pcre_jit on;

events {
    worker_connections 65536;
    multi_accept on;
}

http {
    access_log off;
    server_tokens off;
    msie_padding off;
    etag off;

    types {
        text/html                            html htm;
        text/css                             css;
        
        application/javascript               js;
        application/json                     json;

        image/webp                           webp;
        image/svg+xml                        svg;

        font/woff2                           woff2;
    }

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    keepalive_requests 1000000;
    client_max_body_size 25m;
    client_body_buffer_size 25m;

    gzip on;
    gzip_static on;
    gzip_min_length 100;
    gzip_comp_level 1; 
    # brotli 7 is similar to gzip 5 in compression ratio but much faster, so we set gzip to 5 to save CPU while still getting good compression
    # Not text/plain :(
    # text/html is included automatically when gzip is enabled
    gzip_types  application/json
                application/javascript
                text/css
                image/svg+xml;
    
    brotli on;
    brotli_static on;
    brotli_comp_level 1;
    brotli_min_length 256;
    brotli_types  application/json
                  application/javascript
                  text/css
                  image/svg+xml;

    server {
        listen 8080 reuseport;

        location / {
            httparena;
        }

        location /static/ {
            root /data;
            add_header    Last-Modified '';
        }
    }

    server {
        listen 8443 ssl reuseport;
        listen 8443 quic reuseport;
        http2 on;
        http3 on;

        ssl_certificate /certs/server.crt;
        ssl_certificate_key /certs/server.key;
        ssl_protocols TLSv1.3;
        ssl_session_tickets on;
        ssl_session_cache shared:SSL:10m;

        http2_max_concurrent_streams 256;
        keepalive_requests 10000000;

        add_header Alt-Svc 'h3=":8443"; ma=86400';

        location / {
            httparena;
        }

        location /static/ { 
            root /data;
            add_header    Last-Modified '';
        }
    }
}
