worker_processes auto;
worker_rlimit_nofile 65536;

events {
    worker_connections 65536;
    multi_accept on;
}

http {
    access_log off;
    error_log /dev/null crit;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    keepalive_requests 1000000;
    server_tokens off;
    client_max_body_size 25m;
    client_body_buffer_size 25m;

    gzip on;
    gzip_types application/json;
    gzip_min_length 100;
    gzip_comp_level 1;

    server {
        listen 8080 reuseport;

        location / {
            httparena;
        }
    }

    server {
        listen 8443 ssl reuseport;
        listen 8443 quic reuseport;
        http2 on;
        http3 on;

        ssl_certificate /certs/server.crt;
        ssl_certificate_key /certs/server.key;
        ssl_protocols TLSv1.3;

        add_header Alt-Svc 'h3=":8443"; ma=86400';

        location / {
            httparena;
        }
    }
}
