server.port=8080
server.http2.enabled=false
spring.main.banner-mode=off
logging.level.root=WARN

server.tomcat.max-connections=65536
server.tomcat.accept-count=65536

server.compression.enabled=true
server.compression.mime-types=application/json
server.compression.min-response-size=1024

# TLS + HTTP/2 on port 8443 configured programmatically
