user www-data;
worker_processes auto;
worker_cpu_affinity auto;
worker_rlimit_nofile 65536;
error_log stderr error;
timer_resolution 1s;
daemon off;
pcre_jit on;

events {
    worker_connections 65536;
    multi_accept off;
}

http {
    access_log off;
    server_tokens off;
    msie_padding off;

    types {
        text/html                            html htm;
        text/css                             css;
        application/javascript               js;
        application/json                     json;
        image/jpeg                           jpeg jpg;
        image/png                            png;
        application/pdf                      pdf;
        application/atom+xml                 atom xml;
    }

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    keepalive_requests 1000000;
    client_max_body_size 25m;
    client_body_buffer_size 25m;

    gzip on;
    gzip_types application/json;
    gzip_min_length 100;
    gzip_comp_level 1;

    php_ini_path php.ini;

    init_worker_by_php 'require "app.php";';

    access_by_php 'guard();';

    server {
        listen 8080 reuseport;

        location =/baseline11 { content_by_php 'baseline();'; }
        location =/json { content_by_php 'json();'; }
        location =/pipeline { content_by_php 'pipeline();'; }
        location =/upload { content_by_php 'upload();'; }
        #location =/compression { content_by_php 'compression();'; }
        #location =/db { content_by_php 'db();'; }
        #location /static/ { root /; }
    }

    server {
        listen 8443 ssl reuseport;
        listen 8443 quic reuseport;
        http2 on;
        http3 on;

        ssl_certificate /certs/server.crt;
        ssl_certificate_key /certs/server.key;
        ssl_protocols TLSv1.3;
        ssl_session_tickets on;
        ssl_session_cache shared:SSL:10m;

        http2_max_concurrent_streams 256;
        keepalive_requests 10000000;

        add_header Alt-Svc 'h3=":8443"; ma=86400';

        location =/baseline2 { content_by_php 'baseline();'; }
        #location /static/ { root /; }
    }
}